# SmartShulkers Configuration
sounds:
  pickup: "entity.item.pickup"
  garbage: "block.lava.extinguish"
  sell: "entity.player.levelup"
  error: "block.anvil.break"
permissions:
  craft_smartshulker: "smartshulkers.craft.smartshulker"
  craft_garbageshulker: "smartshulkers.craft.garbageshulker"
  craft_sellshulker: "smartshulkers.craft.sellshulker"
  modify_smartshulker: "smartshulkers.modify.smartshulker"
  modify_garbageshulker: "smartshulkers.modify.garbageshulker"
  modify_sellshulker: "smartshulkers.modify.sellshulker"
  sell_command: "smartshulkers.sell"
settings:
  general:
    sound:
      source: VOICE # Available options can be found on https://jd.papermc.io/paper/1.21.5/org/bukkit/SoundCategory.html
      volume: 1.0
      pitch: 1.0
    ignore-items:
      with-name: false
      with-lore: true
      named:
        - "Ignore me :3" # If the user picks up an item with this name, it will be ignored by all shulkers
        - "/Very Cool .*/i" # Also supports regex (this will ignore any item that starts with "VeRy cOoL " and is case-insensitive)
      with-cmd: true # If items with custom_model_data should be ignored
  smartshulker:
    name: "<gradient:gold:yellow>SmartShulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Accepts:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      contents: "<green>Picked up <amount> <item>!"
      error: "<red>This item cannot be added to Smart Shulkers!"
  garbageshulker:
    name: "<gradient:red:dark_red>Garbage Shulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Destroys:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      contents: "<red>Deleted <amount> <item>!"
      error: "<red>This item cannot be added to Garbage Shulkers!"
  sellshulker:
    name: "<gradient:green:dark_green>Sell Shulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Sells:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      sell: "<green>Sold <amount> <item> for <price>!"
      error: "<red>This item cannot be sold!"
    sell_when: INSTA # Options: FULL, LAST_SLOT, STACK, INSTA