# SmartShulkers Configuration
sounds:
  pickup: "entity.item.pickup"
  garbage: "block.lava.extinguish"
messages:
  pickup: "<green>Picked up <amount> <item>!"
permissions:
  craft_smartshulker: "smartshulkers.craft.smartshulker"
  craft_garbageshulker: "smartshulkers.craft.garbageshulker"
  modify_smartshulker: "smartshulkers.modify.smartshulker"
  modify_garbageshulker: "smartshulkers.modify.garbageshulker"
settings:
  smartshulker:
    name: "<gradient:gold:yellow>SmartShulker</gradient>"
    enabled: true
  garbageshulker:
    name: "<gradient:red:dark_red>Garbage Shulker</gradient>"
    enabled: true