# AutoShulker Configuration
sounds:
  pickup: "entity.item.pickup"
  garbage: "block.lava.extinguish"
messages:
  pickup: "<green>Picked up <amount> <item>!"
permissions:
  craft_autoshulker: "smartshulkers.craft.autoshulker"
  craft_garbageshulker: "smartshulkers.craft.garbageshulker"
  modify_autoshulker: "smartshulkers.modify.autoshulker"
  modify_garbageshulker: "smartshulkers.modify.garbageshulker"
settings:
  autoshulker:
    name: "<gradient:gold:yellow>AutoShulker</gradient>"
    enabled: true
  garbageshulker:
    name: "<gradient:red:dark_red>Garbage Shulker</gradient>"
    enabled: true