# SmartShulkers Configuration
sounds:
  pickup: "entity.item.pickup"
  garbage: "block.lava.extinguish"
  sell: "entity.player.levelup"
  error: "block.anvil.break"
permissions:
  craft_smartshulker: "smartshulkers.craft.smartshulker"
  craft_garbageshulker: "smartshulkers.craft.garbageshulker"
  craft_sellshulker: "smartshulkers.craft.sellshulker"
  modify_smartshulker: "smartshulkers.modify.smartshulker"
  modify_garbageshulker: "smartshulkers.modify.garbageshulker"
  modify_sellshulker: "smartshulkers.modify.sellshulker"
  sell_command: "smartshulkers.sell"
settings:
  smartshulker:
    name: "<gradient:gold:yellow>SmartShulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Accepts:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      contents: "<green>Picked up <amount> <item>!"
  garbageshulker:
    name: "<gradient:red:dark_red>Garbage Shulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Destroys:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      contents: "<red>Deleted <amount> <item>!"
  sellshulker:
    name: "<gradient:green:dark_green>Sell Shulker</gradient>"
    enabled: true
    lore:
      accepts: "<gray>Sells:"
      itemnames: "<dark_gray>- <item>"
      empty: "<dark_gray>- None"
    message:
      enabled: true
      type: ACTIONBAR # Valid options: CHAT, ACTIONBAR
      sell: "<green>Sold <amount> <item> for <price>!"
      error: "<red>This item cannot be sold!"
    sell_when: INSTA # Options: FULL, LAST_SLOT, STACK, INSTA