name: SmartShulkers
version: ${version}
main: org.notionsmp.smartshulkers.SmartShulkers
api-version: '1.21'
load: STARTUP
author: "Akis (discord: yeahakis)"
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false